services:
  qwen-vl-api:
    build: .
    ports:
      - "9192:9192"
    volumes:
      - ./app/models:/app/models
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-"all"}
      - QWEN_MODEL: ${QWEN_MODEL:-"Qwen2.5-VL-7B-Instruct"}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9192/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
